name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # === 追加ポイント①: ビルド前に環境変数がちゃんとセットされているか確認 ===
      - name: Print env before build # ← ここを追加
        run: printenv | grep VITE_
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }} # ← Secrets 名と一致しているか注意
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }} # ← Secrets 名を再確認
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # === 追加ポイント②: ビルド後にも確認 ===
      - name: Debug env after build # ← ここも追加可能
        run: |
          echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL"
          echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # === 追加ポイントはここまで！ ===

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JISOU_KADAI_2_F816F }}
          channelId: live
          projectId: jisou-kadai-2-f816f
